---
title: "30 Year Normal Weather"
author: "Kolby Grint"
date: "2/16/2021"
output: pdf_document
---

```{r setup}
library(daymetr)
library(tidyverse)
library(dplyr)
```


```{r data}
arlington<-download_daymet(site= "arlington",
                lat = 43.3091, #The N-S latitude value
                lon = -89.3473, #The E-W longitude value
                start = 1988,#Start of the range of years
                end = 2018,#end of the range of years
                path = ,#Path for where to save the data; default is NULL
                internal = TRUE,
                simplify = TRUE)

str(arlington)
```


```{r data wrangling}
arlington_prcp= arlington %>%
  select(site, tile, year, yday, measurement, value) %>%
  filter(measurement == "prcp..mm.day.") #%>%
  ##mutate(month)

arlington_tmax= arlington %>%
  select(site, tile, year, yday, measurement, value) %>%
  filter(measurement == "tmax..deg.c.") %>%
  rename( c("tmax" = "measurement", "tmaxc" = "value"))
 

arlington_tavg= arlington %>%
  select(site, tile, year, yday, measurement, value) %>%
  filter(measurement == "tmin..deg.c.") %>%
  left_join(arlington_tmax, by = c("site", "tile", "year", "yday")) %>%
  mutate(tmean = (value + tmaxc)/2)

```


```{r}

```

